### ISSUE TITLE
Refactor functions that don't need to return a result 

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#282]
### What is the feature you would like to see?

Previously, all public methods were required to return a Result type with Vec<u8> as the error type. This is now optional. Specifically, if a method is "infallible" (i.e., it cannot produce an error), it does not need to return a Result type.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by 0xNeshi** [comment]
@ggonzalez94 @bidzyyys @qalisander there don't seem to be any "infallible" methods that are left to refactor, can you point out any?

Also, in [this comment](https://github.com/OpenZeppelin/rust-contracts-stylus/pull/311#discussion_r1788083697) Gustavo suggests we update all examples to return explicit `Error` types instead of `Vec<u8>`.
@emnul you can do this as part of this PR - basically, wherever you see that `Result<[return-type], Vec<u8>>` is returned, update it to return an explicit `Result<[return-type], Error>` type, where `Error` is either imported from the inherited contract (e.g. `erc20::Error`), or is a wrapper around multiple errors.

To see how to create wrapper errors, check:

- [Erc20Permit wrapper error definition](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/9192c1849680f0c0f60822ac288b172a8b276c89/contracts/src/token/erc20/extensions/permit.rs#L62-L72)
- [converting an inherited error into a wrapper error](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/main/examples/merkle-proofs/src/lib.rs#L30)

**Comment by emnul** [comment]
Thanks for taking another look at this one @0xNeshi ! I will turn my attention to #327 at this time

**Comment by 0xNeshi** [comment]
@emnul I'll assign you to that issue then, and take over this one :+1:
